### ISSUE TITLE
[FR] Support move sync

### ISSUE THREAD

**Issue by YIRU69** [antoniotejada/obsidian-edit-history#4]
Thanks for the plugin. 

In fact, I have been using this plugin for a while and I am very grateful that it has helped me solve some backup issues. However, during the usage, I have noticed some issues. When I move my notes, their backups remain in the original location. This means I have to locate the backup of each note and then move it to the new location, which is quite inconvenient.
Is it possible to have a feature where backup files move with the original files when I move them? 
Could you enable synchronization between them or support keeping backup files within the same folder?

**Comment by antoniotejada** [comment]
So glad it has helped!

I'm assuming you refer to move and delete from inside Obsidian, not with an external application.

Automatically keeping the history files synchronized with the notes when moving/deleting/renaming from inside Obsidian is supposed to work. Delete and rename work, but looks like there are issues with moving notes.

Leaving open and marking as a bug for the time being until I get back to look into it.

**Comment by YIRU69** [comment]
Yes, Delete and rename work, and single note moving is broken.

**Comment by antoniotejada** [comment]
This is now fixed and released in 0.1.2, thanks @YIRU69 for reporting!
